name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Sprawdź kod z repozytorium
    - name: Checkout code
      uses: actions/checkout@v3

    # Budowanie obrazu Docker
    - name: Build Docker image
      run: |
        docker build -t my-docker-image:latest .

    # Uruchomienie kontenera
    - name: Run Docker container
      run: |
        docker run -d -p 8081:8081 --name my-docker-container my-docker-image:latest

    # Sprawdzenie działania kontenera
    - name: Test Container
      run: |
        curl http://localhost:8081

