name: Build and Run Multi-Architecture Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Sprawdzenie kodu z repozytorium
    - name: Checkout code
      uses: actions/checkout@v3

    # Konfiguracja Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Logowanie do Docker Hub (jeśli wymagane)
    - name: Log in to Docker Hub
      if: secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD
      uses: docker/login-action@v2
      with:
        username: kogonek
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}

    # Budowanie obrazu dla wielu architektur z wykorzystaniem cache
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          my-docker-image:latest
          my-docker-image:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=my-docker-image:cache
        cache-to: type=registry,ref=my-docker-image:cache,mode=max

    # Uruchomienie kontenera (tylko dla bieżącej architektury)
    - name: Run Docker container
      run: |
        docker run -d -p 8081:8081 -e PORT=8081 --name my-docker-container my-docker-image:latest

    - name: Wait for the server to start
      run: sleep 5

    - name: Print Docker container logs
      run: docker logs my-docker-container

    # Testowanie działania kontenera
    - name: Test Container
      run: |
        curl http://localhost:8081


